### ISSUE TITLE
Capacitor 4 version

### ISSUE THREAD

**Issue by mariusvn** [NativeScript/capacitor#18]
Hello,

I am working on an application using capacitor 4. It would help a lot if the capacitor version was bumped to v4.

Thanks for the work !

**Comment by c4ffein** [comment]
Hi,

I have the same problem : using custom NativeScript code instead of a semi-broken capacitor plugin would solve my problem, but the application I am working on is currently using Capacitor 4. I never had problems with @nativescript/capacitor, but since there were only minor changes from Capacitor 3 to 4 I thought it would already be compatible with v4.

I managed to fix some problems executing gradlew in a Capacitor 4 project by bumping minSdkVer and renaming some version number variables, but now the task `:app:runSbg` is failing without additional info and I don't know how to debug gradle scripts efficiently.
The ios build is failing too ofc but I didn't take much time to look into it.

Pinging @NathanWalker to know if that could be resolved fast, otherwise I'll have to write native and not nativescript code on both android and ios.

Thanks for that project in any case

**Comment by NathanWalker** [comment]
@mariusvn @c4ffein marking this in progress; will be next week to triage fully but will be anxious to get back to you here.

**Comment by NathanWalker** [comment]
@mariusvn @c4ffein we are targeting a release week of Oct. 17th (next week) - Planning on matching the version as well to Capacitor version for clarity so will be v4 and we'll plan to always match their major. Further if anything specific you've had issue with please let us know!

**Comment by NathanWalker** [comment]
For context, generally there will be little change with Capacitor versions with NativeScript - the Capacitor v4 compat more had to do with Xcode 14 build phase changes which just affected how the latest NativeScript cocoapod used with @nativescript/capacitor handled in the pre-build step. The only other thing was the post install handling since the v4 Capacitor templates added a `assertDeploymentTarget` step.

**Comment by NathanWalker** [comment]
@mariusvn @c4ffein Let us know if you have any further issue - migration guide noted here:
https://github.com/NativeScript/capacitor/releases/tag/4.0.0

**Comment by c4ffein** [comment]
Thanks a lot! I won't test this rn as I ended up using another solution for that Capacitor project, but I'll use it for the next one.
